services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: airflow
      MYSQL_USER: airflow
      MYSQL_PASSWORD: airflow
      MYSQL_DATABASE: students
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - airflow_network

  redis:
    image: redis:6
    networks:
      - airflow_network

  airflow-webserver:
    image: apache/airflow:2.5.1
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+mysqlconnector://airflow:airflow@mysql:3306/students
      - AIRFLOW__CORE__FERNET_KEY="4aTLsBWK-sy1GqEuTPsEdgNsI0hoNedlQ3jg5W7sZgE="
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
    networks:
      - airflow_network
    depends_on:
      - mysql
      - redis
    command: bash -c "airflow db init && airflow webserver"

  airflow-scheduler:
    image: apache/airflow:2.5.1
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+mysqlconnector://airflow:airflow@mysql:3306/students
      - AIRFLOW__CORE__FERNET_KEY="4aTLsBWK-sy1GqEuTPsEdgNsI0hoNedlQ3jg5W7sZgE="
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
    networks:
      - airflow_network
    depends_on:
      - mysql
      - redis
    command: bash -c "airflow db init && airflow scheduler"

  airflow-worker:
    image: apache/airflow:2.5.1
    environment:
      - AIRFLOW__CORE__EXECUTOR=CeleryExecutor
      - AIRFLOW__DATABASE__SQL_ALCHEMY_CONN=mysql+mysqlconnector://airflow:airflow@mysql:3306/students
      - AIRFLOW__CORE__FERNET_KEY="4aTLsBWK-sy1GqEuTPsEdgNsI0hoNedlQ3jg5W7sZgE="
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
    volumes:
      - ./dags:/opt/airflow/dags
      - ./data:/opt/airflow/data
    networks:
      - airflow_network
    depends_on:
      - mysql
      - redis
    command: celery worker

  jupyter-notebook:
    image: jupyter/pyspark-notebook:latest
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PYSPARK_PYTHON=python3
    ports:
      - "8888:8888"
    volumes:
      - ./mysql-connector-j-8.4.0.jar:/home/jovyan/mysql-connector-j-8.4.0.jar
    networks:
      - airflow_network
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
  data:

networks:
  airflow_network:
    driver: bridge

